pipeline {
	agent none
	options {
		buildDiscarder(logRotator(numToKeepStr: '10'))
	}
	triggers {
		pollSCM 'H/3 * * * *'
	}
	stages {
		stage('Application Build and Test') {
			agent any 
			steps {
				checkout scm
				bat "automation\\ci.bat ${BUILD_NUMBER} ${BRANCH_NAME}"
			}
		}
		stage('Packer Image') {
			when { branch 'master'}
			agent any 
			steps {
				sh "TasksLocal/delivery.sh PACKER"
			}
		}
		stage('CD') {
			when { branch 'master'}
			agent any 
			steps {
				bat "TasksLocal\\delivery.bat ${env.STAGE_NAME}"
			}
		}

		stage ('Test Manager Approval') {
			when { branch 'master'}
			steps {
				timeout(time:1, unit:'DAYS') {
					input message:'Deploy to Acceptence Test?'
				}
			}
		}
		
		stage('TEST') {
			when { branch 'master'}
			agent any 
			steps {
				bat "TasksLocal\\delivery.bat ${env.STAGE_NAME}"
			}
		}

		stage ('Product Owner Approval') {
			when { branch 'master'}
			steps {
				timeout(time:2, unit:'DAYS') {
					input message:'Deploy to Production?'
				}
			}
		}
		
		stage('PROD') {
			when { branch 'master'}
			agent any 
			steps {
				bat "TasksLocal\\delivery.bat ${env.STAGE_NAME}"
			}
		}
	}
    post {
        success {
            echo 'I succeeeded!'
        }
        unstable {
            echo 'I am unstable :/'
			emailext (
				subject: "Jenkins Job Unstable : Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
				body: "${env.BUILD_URL}",
                compressLog: true,
				recipientProviders: [[$class: 'DevelopersRecipientProvider']]
			)
        }
        failure {
            echo 'I failed :('
			emailext (
				subject: "Jenkins Job Failed : Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
				body: "${env.BUILD_URL}",
                attachLog: true,
				recipientProviders: [[$class: 'DevelopersRecipientProvider']]
			)
        }
        changed {
            echo 'Things were different before...'
        }
        always {
            junit '**/target/surefire-reports/*.xml'
        }        
    }	
}
