pipelines:
  default:
    - step:
        name: Build and test
        runs-on:
          - windows
          
          # Custom tags must be ADDITIONAL to the inbuild tags
          # - docker.2019          

        script:

          # Using CDAF Edge
          # - . { iwr -useb https://raw.githubusercontent.com/cdaf/windows/master/install.ps1 } | iex

          # Use Latest Stable
          - . { iwr -useb https://cdaf.io/static/app/downloads/cdaf.ps1 } | iex

          - $env:DOCKER_HOST = ''
          - .\automation\entry.ps1 $env:BITBUCKET_BUILD_NUMBER $env:BITBUCKET_BRANCH

  branches:
    'master':
      - step:
          name: Build and test
          runs-on:
            - windows          
          script:
            - . { iwr -useb https://cdaf.io/static/app/downloads/cdaf.ps1 } | iex
            - $env:DOCKER_HOST = ''
            - .\automation\ci.bat $env:BITBUCKET_BUILD_NUMBER $env:BITBUCKET_BRANCH
          artifacts:
            - "release.ps1"

          # Legacy artefacts
          # artifacts:
          #   - "TasksLocal/**"
          #   - "*.zip"

      - step:
          name: Deploy to test
          runs-on:
            - windows          
          deployment: Test
          script:
            - $env:DOCKER_HOST = ''
            - ./release.ps1 $env:BITBUCKET_DEPLOYMENT_ENVIRONMENT
          
          # Legacy Delivery
          #   - ./TasksLocal/delivery.ps1 $env:BITBUCKET_DEPLOYMENT_ENVIRONMENT

      - step:
          name: Deploy to staging
          deployment: Staging
          script:
            - $env:DOCKER_HOST = ''
            - ./release.ps1 $env:BITBUCKET_DEPLOYMENT_ENVIRONMENT
          
          # Legacy Delivery
          #   - ./TasksLocal/delivery.ps1 $env:BITBUCKET_DEPLOYMENT_ENVIRONMENT

          runs-on:
            - windows          

      - step:
          name: Deploy to production
          runs-on:
            - windows          
          deployment: Production
          trigger: manual
          script:
            - $env:DOCKER_HOST = ''
            - ./release.ps1 $env:BITBUCKET_DEPLOYMENT_ENVIRONMENT
          
          # Legacy Delivery
          #   - ./TasksLocal/delivery.ps1 $env:BITBUCKET_DEPLOYMENT_ENVIRONMENT
