name: $(Rev:r)

trigger:
  branches:
    include:
    - '*'

stages:
- stage: DEV
  displayName: CI
#  variables:
#  - group: Git Reader
  jobs:
  - template: templates/azure-pipelines-build-template.yml

- stage: TEST
  displayName: User Acceptence Test
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
  dependsOn: DEV
#  variables:
#  - group: Test Library Group
  jobs:
  - template: templates/azure-pipelines-deployment-template.yml
    parameters:
      displayName: CD
      environment: TEST

- stage: PROD
  displayName: Production Gated Deployment
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
  dependsOn: TEST
#  variables:
#  - group: Production Library Group
  jobs:
  - template: templates/azure-pipelines-deployment-template.yml
    parameters:
      displayName: CD
      environment: PROD
