# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.guest = :windows
  config.vm.communicator = "winrm"
  config.vm.boot_timeout = 1200  # 20 minutes
  config.winrm.timeout = 1800   # 30 minutes
  config.winrm.max_tries = 20
  config.winrm.retry_limit = 200 # from https://github.com/mitchellh/vagrant/issues/6430
  config.winrm.retry_delay = 10  # from https://github.com/mitchellh/vagrant/issues/6430
  config.vm.graceful_halt_timeout = 600
  # Hyper-V Mount option for Ubuntu https://stackoverflow.com/questions/47000633/ubuntu-17-10-mounting-smb-share-keeps-failing
  #hyper-v: if ENV['VAGRANT_SMB_USER']
  #hyper-v:   config.vm.synced_folder ".", "/vagrant", type: "smb", smb_username: "#{ENV['VAGRANT_SMB_USER']}", smb_password: "#{ENV['VAGRANT_SMB_PASS']}", mount_options:["sec=ntlm","vers=1.0"]
  #hyper-v: else
  #hyper-v:   config.vm.synced_folder ".", "/vagrant", type: "smb", mount_options:["sec=ntlm","vers=1.0"]
  #hyper-v: end
  #hyper-v: config.vm.provider 'hyperv' do |hyperv, override|
  #hyper-v:   hyperv.ip_address_timeout = 600 # 10 minutes
  #hyper-v:   hyperv.auto_start_action = 'Start'
  #hyper-v:   hyperv.linked_clone = true
  #hyper-v:   hyperv.enable_virtualization_extensions = true
  #hyper-v: end
  #virtbox: config.vm.provider 'virtualbox' do |virtualbox, override|
  #virtbox:   virtualbox.linked_clone = true
  #virtbox: end
end
