# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.guest = :windows
  config.vm.communicator = "winrm"
  config.vm.boot_timeout = 900  # 15 minutes
  config.winrm.timeout = 1800   # 30 minutes
  config.winrm.max_tries = 20
  config.winrm.retry_limit = 30
  config.winrm.retry_delay = 10
  config.vm.graceful_halt_timeout = 600
end
