---
project:
  key: YOUREXISTINGPROJECTKEY
  plan:
    key: NEW
    name: The New Key Must be 3 characters
stages:
  - jobs:
      - scripts:
          - "automation\\processor\\buildPackage.bat ${bamboo.buildNumber} ${bamboo.repository.branch.name}"
        interpreter: cmd.exe
#        requirements:
#          - container
        artifacts:
          - name: Package
            path: '*.zip'
          - name: TasksLocal
            path: 'TasksLocal/**'
