---
version: 2

plan:
  project-key: REF
  key: WUC
  name: CDAf Windows Publication

stages:
  - Build Stage:
    - Build Job

Build Job:
  tasks:
    - script:
        - "automation\\processor\\entry.bat ${bamboo.buildNumber} ${bamboo.repository.branch.name}"

  artifacts:
    - name: Package
      pattern: '*.zip'
      shared: true
    - name: TasksLocal
      pattern: 'TasksLocal/**'
      shared: true

---
version: 2

deployment:
  name: WU-CDM
  source-plan: REF-WUC

release-naming:
  next-version-name: ${bamboo.buildNumber}

environments:
  - TEST
  - UAT
  - PROD

TEST:
  triggers:
    - build-success
  tasks:
    - clean
    - artifact-download:
        destination: ${bamboo.working.directory}
    - script:
        - "${bamboo.build.working.directory}\\TasksLocal\\delivery.bat ${bamboo.deploy.environment} ${bamboo.deploy.release}"

UAT:
  triggers:
    - environment-success: TEST
  tasks:
    - clean
    - artifact-download:
        destination: ${bamboo.working.directory}
    - script:
        - "${bamboo.build.working.directory}\\TasksLocal\\delivery.bat ${bamboo.deploy.environment} ${bamboo.deploy.release}"

PROD:
  tasks:
    - clean
    - artifact-download:
        destination: ${bamboo.working.directory}
    - script:
        - "${bamboo.build.working.directory}\\TasksLocal\\delivery.bat ${bamboo.deploy.environment} ${bamboo.deploy.release}"