# If stages is not defined in the .gitlab-ci.yml file, the default pipeline stages are:
#stages:
#  - .pre
#  - build
#  - test
#  - deploy
#  - .post

CI:
  stage: build

  # To use native container runner with CDAF pre-installed
  image: cdaf/windows
  script: entry.ps1 ${CI_PIPELINE_IID} ${CI_COMMIT_BRANCH}

  # Self-hosted Runner
  # tags:
  #   - batch

  # Install Edge Version
  #  script: |
  #    . { iwr -useb https://raw.githubusercontent.com/cdaf/windows/master/install.ps1 } | iex
  #    .\automation\entry.ps1 ${CI_BUILD_ID} ${CI_BUILD_REF_NAME}

  # Install Latest Version
  #  script: |
  #    . { iwr -useb https://cdaf.io/static/app/downloads/cdaf.ps1 } | iex
  #    .\automation\entry.bat %CI_BUILD_ID% %CI_BUILD_REF_NAME%

  artifacts:
    paths:
    - release.ps1

TEST:
  stage: test
  tags:
    - batch
  script: "./release.ps1 $env:CI_JOB_NAME $env:CI_PIPELINE_ID"
  environment: "${CI_JOB_STAGE}"
  dependencies:
    - CI
  only:
    - master

PROD:
  stage: deploy
  tags:
    - batch
  script: "./release.ps1 $env:CI_JOB_NAME $env:CI_PIPELINE_ID"
  environment: "${CI_JOB_STAGE}"
  dependencies:
    - TEST
  only:
    - master
  when: manual

# To apply a hard-dependency on the manual gate, use "needs"
#VERIFY:
#  stage: publish
#  image: cdaf/linux
#  script: |
#    ./release.sh ${CI_JOB_NAME} ${CI_PIPELINE_ID}
#  dependencies:
#    - CI
#    - PROD
#  needs:
#    - CI
#    - PROD
#  only:
#    - main
