stages:
  - build
  - automated
  - manual
  - live

cdaf-ci:
  stage: build

  # To use native container runner with CDAF pre-installed
  image: cdaf/windows
  script: entry.ps1 ${CI_PIPELINE_IID} ${CI_COMMIT_BRANCH}

  # Self-hosted Runner
  # tags:
  #   - batch

  # Install Edge Version
  #  script: |
  #    . { iwr -useb https://raw.githubusercontent.com/cdaf/windows/master/install.ps1 } | iex
  #    .\automation\entry.ps1 ${CI_BUILD_ID} ${CI_BUILD_REF_NAME}

  # Install Latest Version
  #  script: |
  #    . { iwr -useb https://cdaf.io/static/app/downloads/cdaf.ps1 } | iex
  #    .\automation\entry.bat %CI_BUILD_ID% %CI_BUILD_REF_NAME%

  artifacts:
    paths:
    - release.ps1

cd:
  stage: automated
  tags:
    - batch
  script: "./release.ps1 $env:CI_JOB_NAME $env:CI_PIPELINE_ID"
  environment: "${CI_JOB_STAGE}"
  dependencies:
    - cdaf-ci
  only:
    - master

test:
  stage: manual
  tags:
    - batch
  script: "./release.ps1 $env:CI_JOB_NAME $env:CI_PIPELINE_ID"
  environment: "${CI_JOB_STAGE}"
  dependencies:
    - cdaf-ci
  only:
    - master

production:
  stage: live
  tags:
    - batch
  script: "./release.ps1 $env:CI_JOB_NAME $env:CI_PIPELINE_ID"
  environment: "${CI_JOB_STAGE}"
  dependencies:
    - cdaf-ci
  only:
    - master
  when: manual
