name: $(Rev:r)

trigger:
  branches:
    include:
    - '*'

stages:
- stage: DEV
  displayName: ASP.NET Build
  variables:
  - group: Git Reader
  jobs:
  - template: templates/azure-pipelines-build-template.yml

- stage: TEST
  displayName: User Acceptence Test
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
  dependsOn: DEV
  variables:
  - group: Web Deploy Test
  jobs:
  - template: templates/azure-pipelines-deployment-template.yml
    parameters:
      displayName: IIS Deployment Group
      environment: TEST

- stage: PROD
  displayName: Production Gated Deployment
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
  dependsOn: TEST
  variables:
  - group: Web Deploy Production
  jobs:
  - template: templates/azure-pipelines-deployment-template.yml
    parameters:
      displayName: IIS Deployment Group
      environment: PROD
