stages:
  - build
  - automated test
  - manual test
  - live

cdaf-ci:
  stage: build
  tags:
    - batch

#  script: |
#    $env:CDAF_PATH = '.\automation'
#    . { iwr -useb https://raw.githubusercontent.com/cdaf/windows/master/installCDAF.ps1 } | iex
#    .\automation\entry.ps1 $(Build.BuildNumber) $(Build.SourceBranch) staging@$(Build.ArtifactStagingDirectory)

  script: |
    . { iwr -useb https://cdaf.io/static/app/downloads/cdaf.ps1 } | iex
    ./automation/entry.bat %CI_BUILD_ID% %CI_BUILD_REF_NAME%
  artifacts:
    paths:
    - release.ps1

cd:
  stage: automated test
  tags:
    - batch
  script: "./release.ps1 $env:CI_JOB_NAME $env:CI_PIPELINE_ID"
  environment: "${CI_STAGE_NAME}"
  dependencies:
    - cdaf-ci
  only:
    - master

test:
  stage: manual test
  tags:
    - batch
  script: "./release.ps1 $env:CI_JOB_NAME $env:CI_PIPELINE_ID"
  environment: "${CI_STAGE_NAME}"
  dependencies:
    - cdaf-ci
  only:
    - master

production:
  stage: live
  tags:
    - batch
  script: "./release.ps1 $env:CI_JOB_NAME $env:CI_PIPELINE_ID"
  environment: "${CI_STAGE_NAME}"
  dependencies:
    - cdaf-ci
  only:
    - master
  when: manual
