stages:
  - build
  - automated test
  - manual test
  - live

cdaf-ci:
  stage: build
  tags:
    - batch
  script: "automation/ci.bat %CI_BUILD_ID% %CI_BUILD_REF_NAME%"
  artifacts:
    paths:
    - TasksLocal/
    - "%CI_PROJECT_NAME%-%CI_BUILD_ID%.zip"

cd:
  stage: automated test
  tags:
    - batch
  script: "TasksLocal/delivery.bat %CI_JOB_NAME% %CI_PIPELINE_ID%"
  environment: "${CI_JOB_STAGE}"
  dependencies:
    - cdaf-ci

test:
  stage: manual test
  tags:
    - batch
  script: "TasksLocal/delivery.bat %CI_JOB_NAME% %CI_PIPELINE_ID%"
  environment: "${CI_JOB_STAGE}"
  dependencies:
    - cdaf-ci
  only:
    - master

production:
  stage: live
  tags:
    - batch
  script: "TasksLocal/delivery.bat %CI_JOB_NAME% %CI_PIPELINE_ID%"
  environment: "${CI_JOB_STAGE}"
  dependencies:
    - cdaf-ci
  only:
    - master
  when: manual
