---
version: 2

plan:
  project-key: REF
  key: WUC
  name: CDAf Windows Publication

stages:
  - Build Stage:
    - Build Job

Build Job:
  tasks:
    - script:
        interpreter: powershell
        scripts: | # Use latest Published CDAF
          . { iwr -useb https://cdaf.io/static/app/downloads/cdaf.ps1 } | iex
          .\\automation\\entry.bat ${bamboo.buildNumber} ${bamboo.repository.branch.name}

#        scripts: | # Edge version from GitHub
#          $env:CDAF_PATH = '.\automation'
#          . { iwr -useb https://raw.githubusercontent.com/cdaf/windows/master/install.ps1 } | iex
#          .\\automation\\entry.bat ${bamboo.buildNumber} ${bamboo.repository.branch.name}

#        scripts: | # "In-source" implemenation
#          .\\automation\\entry.bat ${bamboo.buildNumber} ${bamboo.repository.branch.name}

  artifacts:
    - name: Package
      pattern: 'release.ps1'
      shared: true

---
version: 2

deployment:
  name: WU-CDM
  source-plan: REF-WUC

release-naming:
  next-version-name: ${bamboo.buildNumber}

environments:
  - TEST
  - UAT
  - PROD

TEST:
  triggers:
    - build-success
  tasks:
    - clean
    - artifact-download:
        destination: ${bamboo.working.directory}
    - script:
        interpreter: powershell
        scripts:
          - ${bamboo.build.working.directory}\\release.ps1 ${bamboo.deploy.environment} ${bamboo.deploy.release}
          - if ( $LASTEXITCODE -ne 0 ) { throw "Script failed with LASTEXITCODE = $LASTEXITCODE" }

UAT:
  triggers:
    - environment-success: TEST
  tasks:
    - clean
    - artifact-download:
        destination: ${bamboo.working.directory}
    - script:
        interpreter: powershell
        scripts:
          - ${bamboo.build.working.directory}\\release.ps1 ${bamboo.deploy.environment} ${bamboo.deploy.release}
          - if ( $LASTEXITCODE -ne 0 ) { throw "Script failed with LASTEXITCODE = $LASTEXITCODE" }

PROD:
  tasks:
    - clean
    - artifact-download:
        destination: ${bamboo.working.directory}
    - script:
        interpreter: powershell
        scripts:
          - ${bamboo.build.working.directory}\\release.ps1 ${bamboo.deploy.environment} ${bamboo.deploy.release}
          - if ( $LASTEXITCODE -ne 0 ) { throw "Script failed with LASTEXITCODE = $LASTEXITCODE" }
