jobs:
  - job: Build
    displayName: Build and Package
    pool:
      vmImage: windows-latest
#      vmImage: windows-2019

#    pool:
#      name: Self-hosted Pool Name

    steps:
      # - task: PowerShell@2
      #   displayName: Diag
      #   inputs:
      #     workingDirectory: $(System.ArtifactsDirectory)/drop
      #     targetType: inline
      #     script: dir ; systeminfo

      - task: PowerShell@2
        displayName: CI Process
#        env: 
#          GIT_USER: $(GIT_USER)
#          GIT_PASS: $(GIT_PASS)
        inputs:

          targetType: 'inline' # Use latest published version
          script: |
            . { iwr -useb https://cdaf.io/static/app/downloads/cdaf.ps1 } | iex
            .\automation\entry.ps1 $(Build.BuildNumber) $(Build.SourceBranch) staging@$(Build.ArtifactStagingDirectory)

#          targetType: 'inline' # Use edge CDAF version from GitHub
#          script: |
#            . { iwr -useb https://raw.githubusercontent.com/cdaf/windows/master/install.ps1 } | iex
#            .\automation\entry.ps1 $(Build.BuildNumber) $(Build.SourceBranch) staging@$(Build.ArtifactStagingDirectory)

#          targetType: 'inline' # Use a specific CDAF version
#          script: |
#            iwr -useb http://cdaf.io/static/app/downloads/WU-CDAF-2.5.3.zip -OutFile WU_CDAF.zip
#            Expand-Archive WU_CDAF.zip
#            .\WU_CDAF\automation\entry.ps1 $(Build.BuildNumber) $(Build.SourceBranch) staging@$(Build.ArtifactStagingDirectory)

#          "In-source" implemenation
#          targetType: filePath
#          filePath: ./automation/entry.ps1
#          arguments: $(Build.BuildNumber) $(Build.SourceBranch) staging@$(Build.ArtifactStagingDirectory)

      - task: PublishBuildArtifacts@1
