jobs:
  - job: 'Build'
    displayName: "MSBuild and NuGet"
    pool:
      vmImage: 'windows-2019'
    steps:
      - script: "automation\\entry.bat \"$(Build.BuildNumber)\" \"$env:Build_SourceBranchName\" \"staging@$env:Build_ArtifactStagingDirectory\""
        env: 
          GIT_USER: $(gitUser)
          GIT_PASS: $(gitPass)
      - task: PublishBuildArtifacts@1
