name: CDAF Targetless CD using hosted agent
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Continuous Integration & Feature Branch Testing
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch all history for all tags and branches
        run: |
          git config remote.origin.url https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git fetch --prune --unshallow

      - name: CDAF
        shell: powershell # pwsh for PowerShell Core
        run: |
          cd ${env:GITHUB_WORKSPACE}

          # Using CDAF Edge
          . { iwr -useb https://raw.githubusercontent.com/cdaf/windows/master/install.ps1 } | iex
          .\automation\entry.ps1 ${env:GITHUB_RUN_NUMBER} ${env:GITHUB_REF}

          # CDAF installed in repo
          # .\automation\entry.ps1 ${env:GITHUB_RUN_NUMBER} ${env:GITHUB_REF}

      - name: Artifact Retention
        uses: actions/upload-artifact@v4
        with:
          name: deploy
          path: release.ps1

  test:
    if: github.ref == 'refs/heads/main'
    name: Compose Test
    needs: build
    runs-on: windows-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: deploy
          path: drop
    
      - name: DOCKER
        shell: powershell # pwsh for PowerShell Core
        run: |
          cd ${env:GITHUB_WORKSPACE}\drop
          .\release.ps1 DOCKER

#  # As at Jul 2021 there is no gating capability in GitHub Actions
#  prod:
#    if: github.ref == 'refs/heads/main'
#    name: Continuous Deploy
#    needs: [build, test]
#    runs-on: windows-latest
#    steps:
#      - name: Download Artifacts
#        uses: actions/download-artifact@v4
#        with:
#          name: deploy
#          path: drop
#    
#      - name: PROD
#        shell: powershell # pwsh for PowerShell Core
#        run: |
#          cd ${env:GITHUB_WORKSPACE}\drop
#          .\release.ps1 PROD

  push:
    if: github.ref == 'refs/heads/main'
    name: Publish Image
    needs: [build, test]
    runs-on: windows-latest
    permissions:
      packages: write
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: deploy
          path: drop
    
      - name: PUSH
        shell: powershell # pwsh for PowerShell Core
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Available for GitHub Container Registry
          CI_REGISTRY_USER: ${{ github.actor }}      # any value when using Personal Access Token, e.g. '.'
          CI_REGISTRY: ${{ vars.CI_REGISTRY }}       # for GitHub Container Registry use ghcr.io
        run: |
          cd ${env:GITHUB_WORKSPACE}\drop
          .\release.ps1 PUSH
