pipelines:
  default:
    - step:
        name: Build and test
        script:
#          - $env:CDAF_INSTALL_PATH = "${env:USERPROFILE}\.cdaf"
#          - . { iwr -useb https://raw.githubusercontent.com/cdaf/windows/master/install.ps1 } | iex
#          - ${env:USERPROFILE}\.cdaf\entry.ps1 $env:BITBUCKET_BUILD_NUMBER $env:BITBUCKET_BRANCH
          - . { iwr -useb https://cdaf.io/static/app/downloads/cdaf.ps1 } | iex
          - $env:DOCKER_HOST = ''
          - .\automation\entry.ps1 $env:BITBUCKET_BUILD_NUMBER $env:BITBUCKET_BRANCH
        runs-on:
          - windows          

  branches:
    'master':
      - step:
          name: Build and test
          script:
            - . { iwr -useb https://cdaf.io/static/app/downloads/cdaf.ps1 } | iex
            - $env:DOCKER_HOST = ''
            - .\automation\ci.bat $env:BITBUCKET_BUILD_NUMBER $env:BITBUCKET_BRANCH
          artifacts:
            - "release.ps1"
          runs-on:
            - windows          

      - step:
          name: Deploy to test
          deployment: Test
          script:
            - $env:DOCKER_HOST = ''
            - ./release.ps1 $env:BITBUCKET_DEPLOYMENT_ENVIRONMENT
          runs-on:
            - windows          

      - step:
          name: Deploy to staging
          deployment: Staging
          script:
            - $env:DOCKER_HOST = ''
            - ./release.ps1 $env:BITBUCKET_DEPLOYMENT_ENVIRONMENT
          runs-on:
            - windows          

      - step:
          name: Deploy to production
          deployment: Production
          trigger: manual
          script:
            - $env:DOCKER_HOST = ''
            - ./release.ps1 $env:BITBUCKET_DEPLOYMENT_ENVIRONMENT
          runs-on:
            - windows          
