name: CDAF Targetless CD using hosted agent
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: CI
    runs-on: Windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch all history for all tags and branches
        run: |
          git config remote.origin.url https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git fetch --prune --unshallow

      - name: Feature Branch Targetless CD
        shell: powershell # pwsh for PowerShell Core
        run: |
          cd ${env:GITHUB_WORKSPACE}

          # Using CDAF Edge
          curl.exe -s https://codeload.github.com/cdaf/windows/zip/refs/heads/master -o windows.zip
          Expand-Archive .\windows.zip .
          .\windows-master\automation\entry.ps1 ${env:GITHUB_RUN_NUMBER} ${env:GITHUB_REF}

          # CDAF installed in repo
          # .\automation\entry.ps1 ${env:GITHUB_RUN_NUMBER} ${env:GITHUB_REF}

      - name: Artifact Retention
        uses: actions/upload-artifact@v1
        with:
          name: deploy
          path: release.ps1

  deliver:
    if: github.ref == 'refs/heads/master'
    name: Continuous Delivery
    needs: build
    runs-on: Windows-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v1
        with:
          name: deploy
    
      - name: DOCKER
        shell: powershell # pwsh for PowerShell Core
        run: |
          cd ${env:GITHUB_WORKSPACE}\deploy
          .\release.ps1 DOCKER

  registry:
    if: github.ref == 'refs/heads/master'
    name: Push to Registry
    needs: build
    runs-on: Windows-latest
    env:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        if: ${{ env.DOCKERHUB_TOKEN }} != null
        with:
          username: cdaf
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: PUSH
        if: ${{ env.DOCKERHUB_TOKEN }} != null
        run: |
          cd ${GITHUB_WORKSPACE}/deploy
          chmod +x release.sh
          ./release.sh PUSH