name: CDAF Targetless CD using hosted agent
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: CI
    runs-on: Windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch all history for all tags and branches
        run: |
          git config remote.origin.url https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git fetch --prune --unshallow

      - name: Feature Branch Targetless CD
        run: |
          cd ${env:GITHUB_WORKSPACE}
          .\automation\entry.bat ${env:GITHUB_RUN_NUMBER} ${env:GITHUB_REF}

      - name: Artifact Retention
        uses: actions/upload-artifact@v1
        with:
          name: deploy
          path: release.ps1

  deliver:
    if: github.ref == 'refs/heads/master'
    name: CD
    needs: build
    runs-on: Windows-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v1
        with:
          name: deploy
    
      - name: DOCKER
        shell: powershell # pwsh for PowerShell Core
        run: |
          cd ${env:GITHUB_WORKSPACE}\deploy
          .\release.ps1 DOCKER
