# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

# This file is used by AtlasPackage.ps1 for verifying CDAF base boxes
if ENV['OVERRIDE_IMAGE']
  vagrantBox = ENV['OVERRIDE_IMAGE']
else
  puts "OVERRIDE_IMAGE not specified! Set environment variable and retry"
  exit 7724 
end

Vagrant.configure(2) do |config|

  # Build Server, fills the role of the build agent and delivers to the host above
  config.vm.define 'test' do |test|
    test.vm.box = "#{vagrantBox}"
    test.vm.provision 'shell', inline: 'Write-Host "pwd    = $(pwd)"'
    test.vm.provision 'shell', inline: 'Write-Host "whoami = $(whoami)"'
    test.vm.provision 'shell', inline: 'systeminfo'

    # Oracle VirtualBox with private NAT has insecure deployer keys for desktop testing
    test.vm.provider 'virtualbox' do |virtualbox, override|
      override.vm.network 'private_network', ip: '172.16.17.100'
    end

    # Microsoft Hyper-V does not support NAT or setting hostname. vagrant up build --provider hyperv
    test.vm.provider 'hyperv' do |hyperv, override|
      hyperv.vmname = "windows-test"
      if ENV['VAGRANT_SMB_USER']
        override.vm.synced_folder ".", "/vagrant", type: "smb", smb_username: "#{ENV['VAGRANT_SMB_USER']}", smb_password: "#{ENV['VAGRANT_SMB_PASS']}, mount_options: ["vers=2.1"]"
      end
    end
  end

end