name: CDAF Targetless CD using hosted agent
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Continuous Integration & Feature Branch Testing
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch all history for all tags and branches
        run: |
          git config remote.origin.url https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git fetch --prune --unshallow

      - name: CDAF
        shell: powershell # pwsh for PowerShell Core
        run: |
          cd ${env:GITHUB_WORKSPACE}
          cp -Recurse .\automation\solution .
          .\automation\entry.ps1 ${env:GITHUB_RUN_NUMBER} ${env:GITHUB_REF}

      - name: Artifact Retention
        uses: actions/upload-artifact@v1
        with:
          name: deploy
          path: release.ps1

  NO_PROP:
    name: Verify nothing attempted when unknown Environment supplied
    needs: build
    runs-on: windows-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4.1.7
        with:
          name: deploy
    
      - name: NO_PROP
        shell: powershell # pwsh for PowerShell Core
        run: |
          cd ${env:GITHUB_WORKSPACE}\deploy
          .\release.ps1 NO_PROP

  WINDOWS:
    name: Decryption Test from Sample
    needs: [build, NO_PROP]
    runs-on: windows-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4.1.7
        with:
          name: deploy
    
      - name: WINDOWS
        shell: powershell # pwsh for PowerShell Core
        run: |
          cd ${env:GITHUB_WORKSPACE}\deploy
          .\release.ps1 WINDOWS
